#!/usr/bin/env python3

#
# Copyright (C) 2023 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import agent
import json
import os
import sys

request = json.load(sys.stdin)

# Store domain name for services configuration:
agent.set_env("LDAP_USER_DOMAIN", request["ldap_domain"])

# Bind the new domain, overriding previous values (unbind)
agent.bind_user_domains([request["ldap_domain"]])
