#!/usr/bin/env python3

#
# Copyright (C) 2023 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import sys
import agent

# Try to parse the stdin as JSON.
# If parsing fails, output everything to stderr
data = json.load(sys.stdin)

# Setup configuration from user input.
agent.set_env("MAIL_SERVER", data["mail_server"])
agent.set_env("ADMIN_USERS", data.get("admin_users","administrator").lower())
agent.set_env("MAIL_DOMAIN",data.get("mail_domain",""))
agent.set_env("WOWORKERSCOUNT",data.get("workers_count","3"))
agent.set_env("AUXILIARYACCOUNT",data.get("auxiliary_account",True))
agent.set_env("ACTIVESYNC",data.get("activesync",True))
agent.set_env("DAV",data.get("dav",True))
agent.set_env("TRAEFIK_HOST", data["host"])
