#!/usr/bin/env python3

#
# Copyright (C) 2023 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import sys
import agent
import os
from pathlib import Path

# try to find the timezone except to UTC
symlink_path = "/etc/localtime"
resolved_path = Path(symlink_path).resolve()
timezone = str(resolved_path.relative_to(Path("/usr/share/zoneinfo")))
if not timezone:
    timezone = "UTC"

# Create default vars
agent.set_env("ACTIVESYNC", True)
agent.set_env("DAV", True)
agent.set_env("DRAFTSFOLDER", "Drafts")
agent.set_env("SOGOFOLDERSSENDEMAILNOTIFICATIONS", "NO")
agent.set_env("SOGOACLSSENDEMAILNOTIFICATIONS", "NO")
agent.set_env("SOGOAPPOINTMENTSENDEMAILNOTIFICATIONS", "YES")
agent.set_env("SOGOENABLEEMAILALARMS", "YES")
agent.set_env("SOGOINTERNALSYNCINTERVAL", "30")
agent.set_env("SOGOMAXIMUMPINGINTERVAL", "3540")
agent.set_env("SOGOMAXIMUMSYNCINTERVAL", "3540")
agent.set_env("SOGOMAXIMUMSYNCRESPONSESIZE", "2048")
agent.set_env("SOGOMAXIMUMSYNCWINDOWSIZE", "100")
agent.set_env("SENTFOLDER", "Sent")
agent.set_env("SESSIONDURATION", "1440")
agent.set_env("SXVMEMLIMIT", "512")
agent.set_env("TIMEZONE", timezone)
agent.set_env("TRASHFOLDER", "Trash")
agent.set_env("WOWATCHDOGREQUESTTIMEOUT", "60")
agent.set_env("BACKUPTIME", "#30 0")
