#!/usr/bin/env python3

#
# Copyright (C) 2023 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import sys
import json
import agent
import os

request = json.load(sys.stdin)
renv = request['environment']

configure_retval = agent.tasks.run(agent_id=os.environ['AGENT_ID'], action='configure-module', data={
    "ldap_domain": renv["LDAP_DOMAIN"],
    "admin_users": renv["ADMIN_USERS"],
    "mail_server": renv["MAIL_SERVER"],
    "mail_domain": renv["MAIL_DOMAIN"],
    "lets_encrypt": renv["TRAEFIK_LETS_ENCRYPT"],
    "host": renv["TRAEFIK_HOST"],
    "workers_count": renv["WOWORKERSCOUNT"],
    "auxiliary_account": renv["AUXILIARYACCOUNT"],
    "activesync": renv["ACTIVESYNC"],
    "dav": renv["DAV"],

})
agent.assert_exp(configure_retval['exit_code'] == 0, "The configure-module subtask failed!")
