name: Test module

on:
  workflow_dispatch:
    inputs:
      debug_shell:
        description: "Debug shell"
        required: true
        type: boolean
  workflow_run:
    workflows: ["Publish images"]
    types: [completed]

jobs:
  run_tests:
    uses: NethServer/ns8-github-actions/.github/workflows/test-module-qemu.yml@feat-qemu-workflows
    with:
      script: test-module.sh
      debug_shell: ${{ github.event.inputs.debug_shell == 'true' || false }}
